spring.application.name=backgts
spring.mvc.view.prefix=/WEB-INF/views
spring.mvc.view.suffix=.jsp
#security.basic.enabled=false

spring.profiles.active=dev
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


jwt.secret=ZjJkZWRjM2Y0YzJmODQxY2YzYmM1M2U1YzY3NjY3N2VjN2Q1MzE1ZGU2YzBkY2Y4YzQ1YzE4NzY2MjY3YjA=
jwt.expiration=14400000

