# PRODUCTION - Les credentials sont injectés par Railway
spring.jpa.show-sql=false
springdoc.swagger-ui.enabled=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=WARN
logging.level.com.gts=INFO
