
#app.cors.allowed-origins=http://localhost:4200
app.cors.allowed-origins=http://localhost:4200,https://gts-frontend-production-6919.up.railway.app

#DEVELOPPMENT
spring.datasource.url = jdbc:mysql://localhost:3306/db_gts?serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
server.port=8081

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sergezingue@gmail.com
spring.mail.password=jfeb ibbh vwcf xmfp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=sergezingue@gmail.com
app.mail.from-name=GTS Application
