app.cors.allowed-origins=https://frontend.mon-domaine.com
###PRODUCTION
#spring.datasource.url = jdbc:mysql://localhost:3306/eventtfg_e24apps_db?serverTimezone=UTC
#spring.datasource.username = eventtfg_eventams
#spring.datasource.password = ww)N0MwkVJ5F